#words for hangman game
words =( "apple", "banana", "cherry", "date", "elderberry", "fig", "grape",
         "honeydew", "kiwi", "lemon", "mango", "nectarine", "orange", "papaya",
         "quince", "raspberry", "strawberry", "tangerine", "watermelon", "apricot",
         "blackberry", "cantaloupe", "dragonfruit", "eggplant", "feijoa", "guava",
         "huckleberry", "imbe", "jackfruit", "kiwano", "lychee", "mulberry",
         "nectarine", "olive", "pomegranate", "quince", "raisin", "starfruit",
         "tamarind", "ugli", "vanilla", "watermelon", "yuzu", "zucchini", "avocado",
         "blackcurrant", "cranberry", "damson", "bear", "crocodile", "elephant",
         "giraffe", "hippopotamus", "jaguar", "kangaroo", "lion", "monkey",
         "orangutan", "penguin", "rhinoceros", "squirrel", "tiger", "vulture",
         "whale", "zebra", "albatross", "butterfly", "caterpillar", "dolphin",
         "elephant", "flamingo", "gorilla", "hummingbird", "iguana", "jellyfish",
         "kangaroo", "lemur", "macaw", "nightingale", "octopus", "parrot",
         "quail", "raccoon", "scorpion", "toucan", "umbrellabird", "vulture",
         "wombat", "xerus", "yak", "zebra", "antelope", "buffalo", "cheetah",
         "dolphin", "elephant", "flamingo", "gazelle", "hippopotamus", "impala",
         "jaguar", "kangaroo", "lemur", "macaw", "nightingale", "octopus",
         "parrot", "quail", "raccoon", "scorpion", "toucan", "umbrellabird")
